version: '3.4'

services:
  mvcgui:
    image: ${DOCKER_REGISTRY-}mvcgui
    build:
      context: .
      dockerfile: MVCGui/Dockerfile
    depends_on:
        - additionService
        - subtractionService
        - additionDatabase
    ports:
    - "8182:80"
  additionService:
    image: ${DOCKER_REGISTRY-}additionservice
    deploy:
      replicas: 1
    build:
        context:  .
        dockerfile: oblAdditionService/Dockerfile
    depends_on:
        - historyService
        - seq
  subtractionService:
    image: ${DOCKER_REGISTRY-}subtractionservice
    deploy:
      replicas: 1
    build:
        context:  .
        dockerfile: oblSubtractionService/Dockerfile
    depends_on:
        - additionDatabase
        - seq
  clearService:
    image: easvdreter/clearservice
    ports:
    - "8181:80"
    build:
      context:  .
      dockerfile: ClearService/Dockerfile
  historyService:
    image: ${DOCKER_REGISTRY-}historyservice
    ports:
    - "8100:80"
    build:
        context:  . 
        dockerfile: oblHistoryService/Dockerfile
    depends_on:
        - additionDatabase
        - seq
  additionDatabase:
    image: "mysql"
    environment: 
      MYSQL_DATABASE: "add-database"
      MYSQL_USER: "add-bruger"
      MYSQL_PASSWORD: "C@ch3d1v2"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411 
    depends_on:
    - additionService
    - mvcgui
    - subtractionService
    - additionDatabase
  seq:
    image: datalust/seq
    ports: 
        - "5341:5341"
        - "5342:80"
    volumes:
        - rps_seq_data1:/data
    environment:
        - ACCEPT_EULA=Y

  
volumes:
  rps_seq_data1:
