version: '3.4'

services:
  mvcgui:
    image: ${DOCKER_REGISTRY-}mvcgui
    build:
      context: .
      dockerfile: MVCGui/Dockerfile
    depends_on:
        - additionService
        - subtractionService
        - additionDatabase
  additionService:
    image: ${DOCKER_REGISTRY-}additionservice
    ports:
    - "8090:80"
    build:
        context:  .
        dockerfile: oblAdditionService/Dockerfile
    depends_on:
        - additionDatabase
  subtractionService:
    image: ${DOCKER_REGISTRY-}subtractionservice
    ports:
    - "8080:80"
    build:
        context:  .
        dockerfile: oblSubtractionService/Dockerfile
  additionDatabase:
    image: "mysql"
    environment: 
      MYSQL_DATABASE: "add-database"
      MYSQL_USER: "add-bruger"
      MYSQL_PASSWORD: "C@ch3d1v2"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
       
